name: "build and lint"
run-name: "Running build and lint"
on:
  pull_request:
    types: [opened]
jobs:
  lint_and_build:
    runs-on: ubuntu-latest
    steps:
      - run: "yarn install"
      - run: "yarn lint"
      - run: "yarn build"
